### ISSUE TITLE
Improve error message when encountering unevolved object

### ISSUE THREAD

**Issue by tzaeschke** [tzaeschke/zoodb#70]
See Test_034_SchemaEvolution.testDataMigrationIssue70.
Currently we may just get an NPE from the DeSerializer:
```
javax.jdo.JDOFatalException: ERROR reading object: 0.0.0.301
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.zoodb.internal.util.ReflTools.newInstance(ReflTools.java:211)
	at org.zoodb.internal.util.DBLogger.newEx(DBLogger.java:97)
	at org.zoodb.internal.util.DBLogger.newEx(DBLogger.java:88)
	at org.zoodb.internal.util.DBLogger.newFatal(DBLogger.java:170)
	at org.zoodb.internal.server.DiskAccessOneFile.readObject(DiskAccessOneFile.java:340)
	at org.zoodb.internal.model1p.Node1P.refreshObject(Node1P.java:166)
	at org.zoodb.api.impl.ZooPC.zooActivateRead(ZooPC.java:373)
	at org.zoodb.test.jdo.TestClassSmall.getMyInt(TestClassSmall.java:35)
	at org.zoodb.test.jdo.Test_034_SchemaEvolution.testDataMigrationIssue70_RecognizeUnevolvedObjects(Test_034_SchemaEvolution.java:380)
NestedThrowablesStackTrace:
java.lang.NullPointerException
	at org.zoodb.internal.DataDeSerializer.deserializeFields1(DataDeSerializer.java:380)
	at org.zoodb.internal.DataDeSerializer.readObjPrivate(DataDeSerializer.java:304)
	at org.zoodb.internal.DataDeSerializer.readObject(DataDeSerializer.java:297)
	at org.zoodb.internal.server.DiskAccessOneFile.readObject(DiskAccessOneFile.java:337)
	at org.zoodb.internal.model1p.Node1P.refreshObject(Node1P.java:166)
	at org.zoodb.api.impl.ZooPC.zooActivateRead(ZooPC.java:373)
	at org.zoodb.test.jdo.TestClassSmall.getMyInt(TestClassSmall.java:35)

```

**Comment by tzaeschke** [comment]
To clarify, ZooDB already throw useful exceptions in case of schema conflicts. But the above case represent a situation where the schemata are actually compatible, but the version is still incorrect. This should cause an exception (for now) because we may have missed out on (semantic) data evolution.
