### ISSUE TITLE
Break is missing in switch (f.getPrimitiveType()) { case CHAR: } at QueryOptimizer.determineIndexToUseSub()

### ISSUE THREAD

**Issue by slavap** [tzaeschke/zoodb#99]
Stack trace:
Exception in thread "main" java.lang.ClassCastException: java.lang.Character cannot be cast to java.lang.Number
        at org.zoodb.internal.query.QueryOptimizer.determineIndexToUseSub(QueryOptimizer.java:279)
        at org.zoodb.internal.query.QueryOptimizer.determineIndexToUse(QueryOptimizer.java:114)
        at org.zoodb.jdo.impl.QueryImpl.runQuery(QueryImpl.java:580)
        at org.zoodb.jdo.impl.QueryImpl.executeWithArray(QueryImpl.java:728)
        at org.zoodb.jdo.impl.QueryImpl.execute(QueryImpl.java:707)
        at com.sip.App.main(App.java:49)

Test case is attached, just rename png to zip.
![zoodbbugs1](https://cloud.githubusercontent.com/assets/4129763/26340382/e8ecdf62-3f42-11e7-8a6d-4c5a3537329b.png)

**Comment by slavap** [comment]
By the way, specifying char value right in the filter condition is not working as well:
q.setFilter("ch == 'a' || ch == 'z'");

**Comment by tzaeschke** [comment]
Nice catch, that certainly qualifies for the bounty.

Btw, you can use the following construct to reset databases:
```
        if (ZooHelper.dbExists(dbName)) {
            ZooHelper.removeDb(dbName);
        }
```

**Comment by tzaeschke** [comment]
I moved the second bug to a separate issue #104.
